package com.google.sps.servlets;

import com.google.api.gax.paging.Page;

import com.google.cloud.datastore.Datastore;
import com.google.cloud.datastore.DatastoreOptions;
import com.google.cloud.datastore.Entity;
import com.google.cloud.datastore.FullEntity;
import com.google.cloud.datastore.KeyFactory;
import com.google.cloud.datastore.Query;
import com.google.cloud.datastore.QueryResults;
import com.google.cloud.datastore.StructuredQuery.OrderBy;
import com.google.cloud.storage.Blob;
import com.google.cloud.storage.BlobId;
import com.google.cloud.storage.BlobInfo;
import com.google.cloud.storage.Bucket;
import com.google.cloud.storage.Storage;
import com.google.cloud.storage.StorageOptions;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.MultipartConfig;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.Part;
import java.util.*;

@WebServlet("/share")
@MultipartConfig
public class ShareMeme extends HttpServlet {
  public static final String PROJECT_ID = "spring21-sps-43";
  public static final String BUCKET_NAME = "spring21-sps-43.appspot.com";
  public static final String LINK = "https://spring21-sps-43.appspot.com/share?meme=";

  /**
  Handles the projection of only one meme. It search with the parameter of memeName the meme with that name
  and return and HTML with the image and the FACEBOOK and TWITTER share buttons of that link
  **/
  
  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
    response.setContentType("text/html;");
    String memeName = request.getParameter("meme");

    // Print the headers, and set the webpage style to match the rest of the website
    PrintWriter out = response.getWriter();
    out.println("<head>");
    out.println("<link rel=\"stylesheet\" href=\"style.css\">");
    out.println("</head>");
    out.println("<div id=\"content\">");
    out.println("<a href=\"/\" class=\"no-underline\">");
    out.println("<h1 class=\"main-page-title \">Meme Generator</h1>");
    out.println("</a>");
    out.println("<a class=\"body-text\">");

    // Instantiate datastore
    Datastore datastore = DatastoreOptions.getDefaultInstance().getService();
    Query<Entity> query = Query.newEntityQueryBuilder().setKind("Meme").build();
    QueryResults<Entity> results = datastore.run(query);

    // find the datastore element with this meme name, and print it
    while (results.hasNext()) {
        Entity entity = results.next();
        if (entity.getString("name").equals(memeName)) {
            out.println("<img class=\"center-image\" src=\"" + entity.getString("url") + "\"/>");
            out.println("<div id=\"fb-root\"></div><script async defer crossorigin=\"anonymous\" src=\"https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v10.0\" nonce=\"ZRUaVmmR\"></script>");
            out.println("<br><div class=\"fb-share-button\" data-href=\"https://spring21-sps-43.appspot.com/share?meme=" + entity.getString("name") + "\" data-layout=\"button_count\"></div>");
            out.println("<a href=\"https://twitter.com/intent/tweet?ref_src=twsrc%5Etfw\" class=\"twitter-hashtag-button\" data-url=\"https://spring21-sps-43.appspot.com/share?meme=" + entity.getString("name") +  "data-show-count=\"false\"></a><script async src=\"https://platform.twitter.com/widgets.js\" charset=\"utf-8\"></script>");
            out.println("<p>User: " + entity.getString("user") + "</p>");
            out.println("<p>Uploaded: " + entity.getString("upload-date"));
            out.println("<p>Likes: " + Long.toString(entity.getLong("likes")));
            out.println("<p>Autogenerated caption: " + entity.getString("caption") + "</p>");
            out.println("<p>Tags: "+ entity.getString("tags") + "</p>");
        }
    }
    out.println("</a>");

    // output the upload meme and see all memes button
    out.println("<form action=\"/memes\" method=\"POST\" enctype=\"multipart/form-data\">");
    out.println("<label for=\"uploadImage\" class=\"upload-button\" style=\"top: 25px;\">Upload Meme</label>");
    out.println("<input type=\"file\" value=\"Upload Meme\" id=\"uploadImage\" name=\"image\" class=\"hidden\" onchange=\"form.submit()\">");
    out.println("</form>");
    out.println("<a href=\"/memes\" class=\"no-underline\">");
    out.println("<p class=\"see-memes-button\" style=\"top: 35px;\">See All Memes</p>");
    out.println("</a>");

    
  }
  
}
